
# Spring Configuration
spring:

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/postdb?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    # Properties
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql: true
        ddl-auto : update
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true
    hibernate:
      ddl-auto: update

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081
